name: assets_control_app
description: Assets Control App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3 # firebase core
  firebase_auth: ^3.3.4 # firebase auth
  cloud_firestore: ^3.1.5 # firebase firestore
  provider: ^6.0.2 # provider state management
  auto_size_text_pk: ^3.0.0 # text responsible

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # images